ploomber/ploomber

- src/ploomber/clients/db.py
- tests/clients/test_clients.py
Addresses https://github.com/ploomber/ploomber/issues/295
> Create folders when using sqlite

- doc/_static/css/custom-theme.css
- doc/_static/js/custom.js
Bash console and iPython previews aren't really eye catching and causing some problems for Unix Shell Standards.
For more details on the fixing process, please look at the issue #401.
> Console and ipython style fix

- doc/user-guide/editors.rst
> editors spell check

- setup.py
- src/ploomber/cli/build.py
- src/ploomber/cli/cli.py
- src/ploomber/cli/examples.py
- src/ploomber/cli/install.py
- src/ploomber/cli/interact.py
- src/ploomber/cli/nb.py
- src/ploomber/cli/parsers.py
- src/ploomber/cli/plot.py
- src/ploomber/cli/report.py
- src/ploomber/cli/status.py
- src/ploomber/cli/task.py
- src/ploomber/telemetry/telemetry.py
- tests/telemetry/test_telemetry.py
Updated a few env detection, more exception catching.
> Stats fixes/updates

- CONTRIBUTING.md
Minor details to smooth out on-boarding
> Contributing updates

- setup.py
Fixes #535 
Did a clean ploomber installation with my branch and no issues running `ploomber examples -n templates/ml-basic -o ml-basic`
> Networkx version issue

- .gitignore
- doc/cookbook/db-config.rst
This PR contributes to https://github.com/ploomber/ploomber/issues/317
> adding cookbook examples

- doc/_templates/layout.html
- doc/_templates/videos.html
Please check the above image for it how looks.
To test the code change locally, please follow the below steps.
- go to doc directory
- run "python -m http.server" and navigate to the index page or videos page
Note: script only works when you load the webpage of HTTP(S).
@edblancas
> Added link to channel and subscribe button

- .gitignore
- doc/CONTRIBUTING.md
This PR contributes to https://github.com/ploomber/ploomber/issues/552
Added starting points plus further reading.
> Adding rst tips

- src/ploomber/spec/taskspec.py
- tests/spec/test_taskspec.py
> Initial fix

- src/ploomber/cli/cli.py
Improved CLI command suggestions using `difflib`
Resolves #618
> Improved CLI command suggestions

- src/ploomber/cli/nb.py
> Updated celll to cell. Fixes #664

- src/ploomber/spec/taskspec.py
- tests/spec/test_dagspec.py
The code changes aim to validate product extension against csv, parquet in Sql scripts and raise the relevant error message.
> Product extension validation - #472

- src/ploomber/cli/cloud.py
- src/ploomber/cli/nb.py
- src/ploomber/sources/notebooksource.py
> Changed typos from 'plomber' to 'ploomber'

- doc/_static/css/custom-theme.css
> Fix left bar scrolling CSS

- doc/api/cli.rst
> Updated documentation for nb cli functionality in similar method as nb --help.

- doc/_static/js/custom.js
> Replace "<br>" with new line "\n"

- src/ploomber/cloud/api.py
- tests/cli/test_cloud_execution.py
- tests/cloud/test_api.py
Fixed #808 with a more explicit error message.
Added test case.
> Better error message when doing cloud status

- doc/get-started/sql-pipeline.rst
Missing info in parallel to the template #684
Closes #684 https://github.com/ploomber/ploomber/issues/684
> Updated info in parallel to the template #684

- src/ploomber/resources/dag_template.html
Change dag scale to 50% to improve the readability of HTML output in colab
Part of the PR ploomber/projects#41
> Change dag scale to 50% to improve the readability of HTML output in colab

- src/ploomber/resources/dag_template.html
> Revert "Change dag scale to 50% to improve the readability of HTML output in colab"

- .github/workflows/ci-integration-macos.yml
- .github/workflows/ci-integration-windows.yml
Add missed python version checks for pygraphviz installation
Patches #861
> add missed python version checks for pygraphviz installation in integration tests

- tests/cli/test_cloud_execution.py
remove unwanted assertion. We can just check the function runs with no issue. 
Closes #881
> cloud logs only test exit condition

- tests/conftest.py
Ignore unexpected permission errors during test suite cleanup in `tmp_directory()`
Closes #862
> Fix `test_plot_with_d3_embed` intermittent test

- src/ploomber/tasks/notebook.py
> remove @requires jupyter annotation

- doc/get-started/basic-concepts.rst
I changed pipeline.yaml.yaml to pipeline.yaml.
Closes #x
> Fixed typo

- doc/_static/css/custom-theme.css
- doc/_templates/macros.html
I made adjustments to the navbar to fix the Algolia button issue.
Closes #https://github.com/ploomber/ploomber/issues/764
> Updated navbar

- tests/cli/test_cloud.py
> remove email onboarding test

- doc/CONTRIBUTING.md
I added added an Algolia Crawler Section to doc/contributing.md. 
Closes #752
> Added an Algolia Crawler Section to doc

- src/ploomber/jupyter/manager.py
- tests/test_jupyter.py
Move actual implementation of `load_dag` to `_load_dag` and handle exceptions for `_load_dag`
Fixes #878
> Handle exceptions in `jupyter.manager.load_dag`

- src/ploomber/executors/parallel.py
- tests/dag/test_dag.py
Added a new start_method argument to Parallel.py and then initiated ProcessPoolExecutor with mp_context where context is default or the given start_method
* I can't connect to GPU locally so I need to test this code on AWS VM.
Closes #882
> start_method added to parallel executor

- src/ploomber/__init__.py
- src/ploomber_cli/__init__.py
Remove Python 3.6 deprecation warnings after new releases
#926
> Remove Python 3.6 deprecation warnings

- README.md
- doc/user-guide/faq/plot.rst
- setup.py
- src/ploomber/cloud/api.py
- src/ploomber/io/_commander.py
- src/ploomber/util/dotted_path.py
- tests/assets/doctests/nb.ipynb
- tests/assets/sample_tasks/sample.ipynb
updated documentation to reflect python 3.6 not being supported
removed workarounds for python 3.6
Closes #819
> deprecate python 3.6 (#819)

- src/ploomber/telemetry/telemetry.py
Argo's comment was incorrect, referred to Airflow.
> Updated the telemetry's documentation.

- tests/onboard/test_onboard.py
Added a few unit tests.
However, this is a bit different from what i thought the tests should be.  I was thinking about an end2end test testing whether a correct user action would lead to the correct next step, vice versa. 
I couldn't find a way to do that. So for now, I am mocking every external calls and other functions to make sure the entire workflow runs once and check we have corresponding outputs.
Closes #799
> Tutorial unit test

- .github/workflows/ci-unit-linux.yml
- .github/workflows/ci-unit-macos.yml
- .github/workflows/ci-unit-windows.yml
- CONTRIBUTING.md
added branch filter, updated contribute.md
Closes #820 #954
> added branch filter for CI and proper documentation

- doc/get-started/basic-concepts.rst
- doc/user-guide/jupyter.rst
Added the links defined in #573 
Closes #573
> Add the links

- requirements-colab.lock.txt
Update Jinja2 (dependecy of nbconvert) and MarkupSafe (a dependency of Jinja2) version for colab 
Part of ploomber/projects#56
> update colab Jinja2 and MarkupSafe versions

- CONTRIBUTING.md
adds information on locally running github actions
Closes #x
> add info on locally running github actions

- doc/requirements.txt
- requirements-colab.lock.txt
Solving dependency bot PRs
- [v] I have performed a self-review of my code
- [v] I have added thorough tests (when necessary).
- [v] I have added the right documentation (when needed). Product update? If yes, write one line about this update.
> updating mistune and nbconvert dependencies

- setup.py
- tests/cli/test_custom.py
I mocked the interact class 
Closes #479
> Mocked the interact class

- README.md
> change Get Started button link to binder

- doc/get-started/index.rst
- doc/hooks.py
> add intro tutorial

- doc/CONTRIBUTING.md
https://github.com/ploomber/ploomber/blob/master/doc/CONTRIBUTING.md
line51: layour -> layout
Closes #x
> fixed a small typo

- src/ploomber/cloud/api.py
The function is failing due to missing SSL certificate, changed the url parsing mechanism.
NA
> Fixing the cloud download function

- src/ploomber/cloud/api.py
- tests/cli/test_cloud_execution.py
Fixing api._download_file function, issue when downloading the files from the cloud (no certificate).
> Adjusted api._download_file function

- src/ploomber/cli/io.py
- src/ploomber/executors/parallel.py
- tests/cli/test_examples.py
- tests/cli/test_io.py
added code to show full traceback when raising a non-subclass exception.
Closes #794
> Cli hiding traceback

- .gitignore
- doc/_static/css/custom-theme.css
- doc/_templates/layout.html
- doc/_templates/macros.html
- src/ploomber/cloud/api.py
The right bar in the mobile layout has been improved for a better user experience
Original PR [1014](https://github.com/ploomber/ploomber/pull/1014)
Changes
1. Old right bar's action removed to the bottom of the top navbar
2. Duplicated actions removed (Cloud, Community, and Search)
4. Search icon added to navbar
5. Document navigation button added to navbar
6. Design improved
Document navigation bar open
Search
Closes #366
> Right bar in docs

- doc/_static/css/custom-theme.css
Adds highlighting for anchor  section
https://user-images.githubusercontent.com/41731424/193464713-3d3e0604-c9e2-4194-bc88-3626d4aa2d5c.mp4
Closes #773
> Add highlighting to the anchored section

- doc/get-started/basic-concepts.rst
@idomic 
I have added the parameterized exemple in the `basic-concepts.rst` for documentation as in the issue #965.
Related to #965
> added param example on documentation

- doc/_static/js/custom.js
Added a condition to check if there is at least a section to show then only popping from current list
Closes #767
> Handling console error when right bar does not appear

- doc/cloud/index.rst
- doc/hooks.py
**Notes:**
- I ran some issues with the `invoke` command for the docs environment (it broke my whole environment), so I'm sending the PR expecting to test the modifications in code review.
Closes https://github.com/ploomber/pcloud-backend/issues/157
> Adds hooks to cloud notebooks in projects

- doc/cloud/index.rst
- doc/cloud/pipelines-api-user-guide.rst
- doc/hooks.py
Updates section names according to https://github.com/ploomber/ploomber/issues/1046#issuecomment-1323843845:
> ### Section names
> 
> * Notebooks API getting started
> * Notebooks API user guide
> * Pipelines API getting started
> * Pipelines API user guide
Closes https://github.com/ploomber/ploomber/issues/1046
> Updates cloud notebooks sections

- src/ploomber/cli/nb.py
- tests/assets/nbs-priority-inject/module.py
- tests/assets/nbs-priority-inject/pipeline.yaml
- tests/assets/nbs-priority-inject/pipeline_with_functions.yaml
- tests/cli/test_nb.py
Allow injecting only NotebookRunner tasks
Closes #1048
> Inject only NotebookRunner tasks

- README.md
- doc/_templates/macros.html
Fix blog link incorrect in doc
Closes #1065
> Fix: Blog Link incorrect in Doc Header

- doc/community/user-stats.rst
Update user-stats doc in Community, respond to https://github.com/ploomber/jupysql/issues/72
- Polish the structure
- Add setting environment variable section (Per [#72 of jupyter issue](https://github.com/ploomber/jupysql/issues/72))
Before:
After:
Closes #x
> Doc: User Statistic improvement

- .github/workflows/rtd.yml
> adds rtd config

- CHANGELOG.md
- doc/cookbook/index.rst
- doc/cookbook/nb_executors.rst
- src/ploomber/tasks/notebook.py
- tests/tasks/test_notebook.py
* Added support for ploomber-engine
* Formatted and Linted Code
* Added ploomber engine to testing
* Formatted
* Changelog
* Fixed
* Version
* Added guide
* Added index
* Fix
* Update CHANGELOG.md
* Engine Parameter
* Added sample pipeline
* Fix Indent
* Changed from engine to executor
* Format
* nb_executor -> executor_params
* Fix tests and naming
* Format
* Engine cookbook changes
* renamed
* Fix
* Modified test
* Added ValueError for undefined executor
* Modified guide
* Fix
* Minor
* Reformat
* Format
---------
Closes #X
----
:books: Documentation preview :books:: https://ploomber--1108.org.readthedocs.build/en/1108/
> Add support for ploomber engine (#1101)

- CHANGELOG.md
- src/ploomber/util/markup.py
Closes #X
----
:books: Documentation preview :books:: https://ploomber--1115.org.readthedocs.build/en/1115/
> compatibility with mistune 3

- doc/user-guide/cli.rst
- src/ploomber_cli/cli.py
Added the warning and note for cloud deprecation
Closes #1111
I am having trouble building the docs. Otherwise seems to be fine.
----
:books: Documentation preview :books:: https://ploomber--1113.org.readthedocs.build/en/1113/
> deprecates cloud api

- .github/workflows/binder-badge.yml
Changed the binder-badge workflow file to comment binder-link to new PRs
Closes #1119 
----
:books: Documentation preview :books:: https://ploomber--1120.org.readthedocs.build/en/1120/
---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
- https://app.asana.com/0/0/1204894725737870
> Binder workflow

- CHANGELOG.md
- setup.py
- src/ploomber/jupyter/dag.py
- src/ploomber/sources/notebooksource.py
- src/ploomber/tasks/notebook.py
- src/ploomber/util/dotted_path.py
- tests/tasks/test_notebook.py
- tests/test_jupyter.py
- tests/util/test_dotted_path.py
Closes #1109 
----
:books: Documentation preview :books:: https://ploomber--1123.org.readthedocs.build/en/1123/
> Cleanup tests

- CHANGELOG.md
- src/ploomber/cli/install.py
- tests/cli/test_install.py
…ersion of `ploomber-core`
Closes #X
----
:books: Documentation preview :books:: https://ploomber--1135.org.readthedocs.build/en/1135/
> ploomber install fix

- doc/environment.yml
- doc/requirements.txt
Closes #1157 
----
📚 Documentation preview 📚: https://ploomber--1158.org.readthedocs.build/en/1158/
> Fix docs build
