ploomber/ploomber

README.rst

Fix typo for the documentation link in README.rst.

Fix typo in the README

---

src/ploomber/products/metaproduct.py
tests/products/test_metaproduct.py

Contributes to 
https://github.com/ploomber/ploomber/issues/357 
Summary: modified metaproduct.py
```
def task(self, value):
for p in self.products:
if hasattr(p, 'task'):
p.task = value
continue
else:
raise TypeError(f"It doesn't look like a Product instance, got object of type {type(p)}")
```
currently working on adding test to https://github.com/ploomber/ploomber/blob/master/tests/products/test_metaproduct.py

Catch error when p does not have attribute Task

---

.gitignore

Can we exclude PyCharm's config folder just like we do with VSCode's?

Update .gitignore to exclude .idea/

---

.github/workflows/ci-mac.yml
.github/workflows/ci-windows.yml
.github/workflows/ci.yml
tests/telemetry/test_telemetry.py

I disabled the stats in the CI. Needed to change some of the telemetry_tests (just minor changes). Please review for your awareness.
I also saw you're working on the stats improvements, once this PR is merged, you may want to rebase to get the new `test_telemetry.py`

disaable stats from CI

---

doc/user-guide/jupyter.rst

Add instructions on how to configure `JupyterLab` to open `.py` files as notebooks with a single click

---

src/ploomber/entrypoint.py
tests/test_entrypoint.py

Improved error message when pipeline.yaml does not exist using `pathlib.Path`.
Resolves #509

Improved error message when pipeline.yaml does not exist

---

src/ploomber/products/_resources.py
tests/test_resources.py

PR for Issue #429
changes in the PR:
- implementation of `_check_file_size(path)` warns user about file > 1MB
- function call before calculating hashing of resource file
-----
**pipeline.yaml**
```yaml
tasks:
- source: tasks.raw.get
product: products/raw/get.csv
params:
resources_:
file: conf.yaml
.....
```
**conf.yaml**: dummy file with ~9MB of data
**script used to test**:
```python
def get(resources_, product):
print(" -------------- Debug --------------")
print(open(resources_['file']).read()[:10])
....
```
**output**:
`File too large. Resource <DIR-PATH>/conf.yaml[9.98MB] > 1MB`

fix: warn large resource issue#429

---

doc/api/spec.rst
src/ploomber/env/envdict.py
src/ploomber/env/expand.py
src/ploomber/repo.py
src/ploomber/spec/dagspec.py
tests/cli/test_custom.py
tests/cli/test_nb.py
tests/conftest.py
tests/env/test_env.py
tests/env/test_sample_project_expanders.py
tests/spec/test_dagspec.py
tests/test_repo.py

This PR improves the `{{git}}` placeholder feature:
* Adds `{{git_hash}}` which is slightly different in behavior
* Outputs better error messages (e.g. git not installed, not in a valid repo)
* No longer requires an `env.yaml`: the placeholder can be directly used in `pipeline.yaml`
For a usage example, see: https://github.com/ploomber/projects/blob/versioning/guides/versioning/README.ipynb

Improvements to the {{git}} placeholder feature

---

src/ploomber/spec/dagspec.py
tests/spec/test_dagspec.py

Issue #669
Changes:
When loading `import_tasks_from: file.yaml`
1. If `yaml.safe_load` is None, replace it with an empty list
2. If `yaml.safe_load` returns something other than a list, raise an error saying we were expecting a list

Added validation checks for import_tasks_from

---

src/ploomber/sources/notebooksource.py
tests/sources/test_notebooksource.py
tests/tasks/test_notebook.py

This CR includes changes that make `NotebookRunner` initialized with a String explicitly throw an exception if the string looks like a `pathlib.Path`
```sh
$ pytest tests/sources/test_notebooksource.py -k 'test_error_if_source_str_like_path'
============================================================ test session starts ============================================================
platform linux -- Python 3.7.11, pytest-7.1.1, pluggy-1.0.0
rootdir: /home/vagrant/ploomber, configfile: pyproject.toml
plugins: cov-3.0.0, anyio-3.5.0
collected 87 items / 86 deselected / 1 selected
tests/sources/test_notebooksource.py .                                                                                                [100%]
================================================ 1 passed, 86 deselected, …
```

Improve error message when NotebookRunner initialized with a String

---

src/ploomber/cli/cloud.py
src/ploomber/config.py
src/ploomber/telemetry/telemetry.py
tests/cli/test_cloud.py
tests/telemetry/test_telemetry.py
tests/test_config.py

I refactored the logic to store and retrieve the data from the config files. This is a pre-requisite to start working on the improved onboarding workflow where we have a "tutorial" to point to the user what do to next since we need to add a few extra flags to the config files to track the state.
The tests remain unchanged (I only modified a few and deleted some that are outdated)

Refactors config files

---

src/ploomber_cli/cli.py
tests/cli/test_suggest_command.py

Previously, when a user input an incorrect nested command for `ploomber cloud`, ploomber cli didn't suggest a close match for the nested command. This PR enables nested command suggestion for the ploomber cloud command options (ie get-key, get-pipelines, etc)
2 files changed - 1 includes the updated cli functionality and added 2 new tests.
Issue for reference: https://github.com/ploomber/ploomber/issues/639

add ploomber cloud nested suggestion for cli

---

tests/cli/test_cloud.py

For [issue 758](https://github.com/ploomber/ploomber/issues/758):
Added pytest fixture in test_cloud.py to save the contents of config.yaml before the test and restore them after the test is completed

Save User Setting in Cloud set-key tests

---

src/ploomber/sources/notebooksource.py

dismiss "Black is not installed, parameters wont be formatted" message with logging module.
Since flake8 will complain about putting classes before other imports. I moved it down. Two lines in between are also mandated.
Closes #661
- No tests are needed
- Not a product update. Just a small enhancement.

Suppress black is not installed message

---

src/ploomber/cli/parsers.py
src/ploomber/spec/dagspec.py
src/ploomber/util/default.py
tests/spec/test_dagspec.py
tests/util/test_default.py

When users have pipeline, env file ends with .yml extension, output error message reminding them to rename to .yaml instead.
Closes #659

error message when .yml found instead of .yaml

---

.github/workflows/ci-integration.yml
.github/workflows/ci-unit.yml
.github/workflows/ok-to-test.yml

Added three files, ci-integration.yaml, ci-unit.yaml, ok-to-test.yaml.
Still need to test it on some branch, ideally master branch.
Closes #717

Added /ok-to-test function, reformatted CI

---

doc/cloud/monitoring.rst

Fix typo in Cloud documentation. Should be `write-pipeline` command 
`ploomber cloud write-pipeline <YOUR_PIPELINE_ID> <PIPELINE_STATUS>`
which is defined in https://github.com/ploomber/ploomber/blob/ff4bbda39b57101eea4c18eae7911585d90b5831/src/ploomber/cli/cloud.py#L114-L125
N/A

Fix write-pipeline typo in Cloud documentation

---

tests/cli/test_nb.py
tests/conftest.py
tests/env/test_sample_project_expanders.py

I was having an issue where the tests would ask for my gpg passphrase to sign commits during the tests which isnt ideal
I added a line before the tests to disable gpg signing in the git config
Would be better if global state could be ignored entirely but this fixes
the tests asking for gpg passphrases
Closes #x

Disable commit signing in tests

---

src/ploomber/spec/taskspec.py
tests/spec/test_taskspec.py

1. "_looks_like_path" checks a path. I've added another check if the user passed just a file name (is_path is false). We check if this file has a known extension with mimetypes. If so, this should throw the appropriate error ("Invalid extension"). Otherwise, it might be a dotted path.
2. "If you meant to import a function, please rename it." added at the end of the existing error message since there's a slight chance of a false positive where the user really wants to import a function named as the file's extension. 
3. A single file name without a path added to existing test function (test_task_class_from_script_unknown_extension)
Issue number: 646
Closes #646 
- [X ] I have performed a self-review of my code
- [X ] I have added thorough tests (when necessary).

Fixed confusing error when passing something.html as source #646

---

doc/_static/js/custom.js

Added the title of the terminal to the clickable area for copying terminal text in the docs.
Closes https://github.com/ploomber/projects/issues/51

copy when click on title of terminal in docs

---

CHANGELOG.md
src/ploomber/cli/task.py
src/ploomber/exceptions.py
src/ploomber/executors/_format.py
src/ploomber/messagecollector.py
tests/test_messagecollector.py
tests/tests_util.py

Uses _format to format errors in individual tasks
Closes #828 
I'm not sure if these changes get the behavior we want:
Here I have an example open and I have run `ploomber build`. I then run `ploomber task fit`:
Before _format:
```
(ploomber) conda-shell-chrootenv:prem@morokei:~/Documents/projects/ploomber/ploomberw/test/example$ ploomber task fit
Loading pipeline...
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4/4 [00:00<00:00, 16054.75it/s]
Traceback (most recent call last):
File "/home/prem/Documents/projects/ploomber/ploomberw/ploomber/src/ploomber/tasks/abc.py", line 554, in _build
res = self._run()
File …
```

clean traceback when using ploomber task (#828)

---

CHANGELOG.md
src/ploomber/sources/notebooksource.py
src/ploomber/spec/dagspec.py
src/ploomber/tasks/notebook.py
tests/cli/test_nb.py
tests/sources/test_notebooksource.py
tests/tasks/test_notebook.py
tests/tasks/test_scriptrunner.py

* Change exception to warnings for missing cells in `_post_init_validation`
* Update exception tests `test_error_if_parameters_cell_doesnt_exist` and `test_error_missing_params_cell_shows_path_if_available` to check warnings instead
* Create a method `_validate_parameters_cell` in the class NotebookMixin in `src/ploomber/tasks/notebook.py` to check and add parameter cells if missing
Closes #950

Remove parameters cell missing exception and add cell when it is missing instead

---

src/ploomber/executors/parallel.py
src/ploomber/executors/serial.py
src/ploomber/sources/notebooksource.py
src/ploomber/telemetry.py

I updated examples in api/executors/serial.py and  api/executors/parallel.py to illustrate that `DAGBuildEarlyStop` allows build to exit gracefully, and added doc strings for private methods in serial.py.
Closes #953

Dag gracefully exit doc

---

src/ploomber/spec/dagspec.py
src/ploomber/spec/taskspec.py
tests/spec/test_dagspec.py
tests/spec/test_taskspec.py

The aim here is to be able to dynamically set clients based on the `env.yaml`. In some cases, for example the `File` client one might not want to set a client in the dev environment but might want to backup to the Cloud in production. This allows for that by setting
env.dev.yaml:
```
file_client: ~
```
env.prod.yaml:
```
file_client: clients.get_client
```
pipeline.yaml
```
clients:
File: "{{ file_client }}"
```
When the client is `~` this basically behaves no differently than if the key was missing in `pipeline.yaml` entirely. 
Closes #1015

Allow for setting `null` clients

---

src/ploomber/tasks/notebook.py
tests/tasks/test_notebook.py

Turns out this wasn't actually a problem, but we weren't testing for it so I added a test.
https://github.com/ploomber/ploomber/issues/980#issuecomment-1241199520
Closes #980

do not display warning when a task has multiple notebook outputs

---

doc/api/spec.rst
doc/get-started/basic-concepts.rst

* Add a note to clarify that the keys of product dictionaries can be given any name, in files  doc/get-started/basic-concepts.rst and doc/api/spec.rst
* Fixing minor typos in both files.
Closes #888

Note on naming of product dict keys, typos

---

src/ploomber/env/envdict.py
tests/env/test_env.py

Previously, if you had nested keys in your `env.yaml` it wasn't possible to override a subset of them.
For example:
`env.yaml`
```yaml
nested:
key_1: value_1
key_2: value_2
```
and
`env.prod.yaml`
```yaml
meta:
import_from: env.yaml
nested:
key_1: new_value_1
```
would result in:
```yaml
nested:
key_1: new_value_1
```
With these changes the result is:
```yaml
nested:
key_1: new_value_1
key_2: value_2
```
This should work to an arbitrary depth.
Closes #x 
- I don't think this really needs any additional docs as this is the expected behaviour I'd have thought?

Merge nested `env` keys when using `import_from`

---

src/ploomber/exceptions.py
src/ploomber/spec/dagspec.py
src/ploomber/spec/taskspec.py
src/ploomber/util/validate.py
tests/spec/test_dagspec.py

I added an example to fix the error message for ValidationError when it fails on account of a missing `product` key.
I implemented it as an exception handler and special named exception in `dagspec.py`.
Closes #628 
I made these test projects to reproduce the behavior I added: [testdata.zip](https://github.com/ploomber/ploomber/files/9699304/testdata.zip)
In case the product will be a data file:
```bash
~/code/ploomber-hack/testdata/no_nb
venv ❯ ploomber build                    
Loading pipeline...
Error: Error validating TaskSpec({'source': 'mytask.sh', 'upstream': None}). Missing keys: 'product'
To fix it, add the missing key (example):
- source: mytask.sh
product: products/data.csv
~/code/ploomber-hack/testdata/no_nb
venv ❯ python ../load_dagspec_no_notebook.py …
```

Add improved error message when missing product key

---

src/ploomber/clients/storage/gcloud.py
src/ploomber/tasks/notebook.py
src/ploomber/tasks/sql.py
src/ploomber/tasks/tasks.py

Fix Noqa issue on multiple docs
Before:
After:
Before:
After:
Before:
After:
Before:
After:
Closes #x

Fix: Noqa coming up on docs

---

README.md

I saw that the img of the badges for the [gh-actions](https://github.com/ploomber/ploomber/actions/runs/6836377132/job/18646532359?pr=1138) (on the job broken-links) in the readme give 404 and I made this PR to solve it.
I don't understand how it was working before, but I changed them as the [gh doc](https://docs.github.com/en/actions/monitoring-and-troubleshooting-workflows/adding-a-workflow-status-badge) says so that they point to the last execution of the main branch ("master" in this case).
Check that `pkgmt check-links --only-404` no longer finds any 404 error. Now it looks like this:
I don't think there is one created
----
:books: Documentation preview :books:: https://ploomber--1140.org.readthedocs.build/en/1140/

fix link to gh-actions badges on readme

---

tests/telemetry/test_telemetry.py

This fixes the telemetry tests to take into account the start event that was removed [this pr on core](https://github.com/ploomber/core/pull/77).
I couldn't get the test `test_install_uses_telemetry` to work local, but it works in the gh-actions. 
Closes #1139
----
:books: Documentation preview :books:: https://ploomber--1141.org.readthedocs.build/en/1141/

modified telemetry tests so that they do not include start event

---

tests/io_mod/test_terminalwriter.py

Investigating why the new version adds `"\x1b[90m\x1b[39;49;00m"` with the pygments 2.14 I came to [this](https://github.com/pytest-dev/pytest/issues/10630) similar pytests issue with the same problem. The solution is to add this to the test.
Closes #1062
----
:books: Documentation preview :books:: https://ploomber--1138.org.readthedocs.build/en/1138/

fix test_code_highlight adding what was missing to the end of the line

---

setup.py

The autopep8 [issue](https://github.com/hhatto/autopep8/issues/689) that caused problems with `pycodestyle` was solved. So unpin the `pycodestyle` version on `setup.py`.
Closes #1131
----
:books: Documentation preview :books:: https://ploomber--1143.org.readthedocs.build/en/1143/

unpin pycodestyle dependencie

---

src/ploomber/jupyter/manager.py

Added md5 parameter to PloomberContentsManager.get and passed it along to super calls.
Small interface changes to adapt to 2.11.0 jupyter_server changes
Closes https://github.com/ploomber/ploomber/issues/1144
----
:books: Documentation preview :books:: https://ploomber--1145.org.readthedocs.build/en/1145/

Update to jupyter_server 2.11.0 API

---

doc/_templates/videos.html

Adding the Jupyter Con from 2023 to the Video section of Ploomber documentation.
https://github.com/ploomber/ploomber/issues/1151
As an aside - the urls in the github pull request template for doing a pull request are no longer valid. (The ones for linting, testing and documenting-changes-and-new-features)
----
:books: Documentation preview :books:: https://ploomber--1152.org.readthedocs.build/en/1152/

Update videos.html to include the Jupyter Con 2023 presentation

---

doc/_static/css/custom-theme.css
doc/_templates/macros.html
doc/environment.yml
doc/requirements.txt

Closes https://github.com/ploomber/doc/issues/76
----
📚 Documentation preview 📚: https://ploomber--1156.org.readthedocs.build/en/1156/

Updated banner
